version: '3.8'

services:
#  web:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}:@${DB_HOST}:{DB_PORT}/${DB_NAME}
#    depends_on:
#      - db
#    volumes:
#      - .:/app
#    command: python server.py

  db:
    image: postgres:15-alpine3.16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5431:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data: